services:
    api:
        image: ghcr.io/cubetiq/nextimg-server:latest
        ports:
            - '3000'
        environment:
            - NODE_ENV=production
            - ALLOWED_REMOTE_DOMAINS=*
            - IMGPROXY_URL=http://imgproxy:8080
            - INTERNAL_URL=http://api:3000
            - DATA_STORE_PATH=/app/store
            - OUTPUT_TTL=3600
        volumes:
            - store-data:/app/store
        healthcheck:
            test: 'wget -qO- http://localhost:3000/_/health || exit 1'
            interval: 2s
            timeout: 10s
            retries: 5
        depends_on:
            imgproxy:
                condition: service_healthy

    imgproxy:
        image: ghcr.io/imgproxy/imgproxy:latest
        environment:
            - IMGPROXY_AUTO_WEBP=true
            - IMGPROXY_AUTO_AVIF=true
            - IMGPROXY_JPEG_PROGRESSIVE=true
            - IMGPROXY_USE_ETAG=true
        healthcheck:
            test: ['CMD', 'imgproxy', 'health']
            interval: 2s
            timeout: 10s
            retries: 5

volumes:
    store-data:
